version: "3.10"

services:
  postgres_db:
    image: postgres:16.2
    container_name: cat_show_postgres
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  cat_show_back:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    depends_on:
      - postgres_db
    volumes:
      - static_volume_back:/usr/src/Cat_show/settings/static
      - media_volume:/usr/src/Cat_show/settings/media
    env_file:
      - .env